cp plots/aud_usd_h1-4agents-4rules-4ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-4agents-4rules-4ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-4agents-4rules-4ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-4agents-4rules-4ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-4agents-4rules-4ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-10agents-10rules-10ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-10agents-10rules-10ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-10agents-10rules-10ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-10agents-10rules-10ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-10agents-10rules-10ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-20agents-20rules-20ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-20agents-20rules-20ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-20agents-20rules-20ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-20agents-20rules-20ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/aud_usd_h1-20agents-20rules-20ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots

cp plots/eur_gbp_h1-4agents-4rules-4ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-4agents-4rules-4ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-4agents-4rules-4ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-4agents-4rules-4ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-4agents-4rules-4ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-10agents-10rules-10ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-10agents-10rules-10ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-10agents-10rules-10ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-10agents-10rules-10ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-10agents-10rules-10ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-20agents-20rules-20ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-20agents-20rules-20ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-20agents-20rules-20ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-20agents-20rules-20ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_gbp_h1-20agents-20rules-20ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots

cp plots/eur_usd_h1-4agents-4rules-4ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-4agents-4rules-4ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-4agents-4rules-4ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-4agents-4rules-4ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-4agents-4rules-4ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-10agents-10rules-10ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-10agents-10rules-10ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-10agents-10rules-10ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-10agents-10rules-10ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-10agents-10rules-10ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-20agents-20rules-20ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-20agents-20rules-20ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-20agents-20rules-20ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-20agents-20rules-20ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/eur_usd_h1-20agents-20rules-20ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots

cp plots/gbp_usd_h1-4agents-4rules-4ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-4agents-4rules-4ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-4agents-4rules-4ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-4agents-4rules-4ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-4agents-4rules-4ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-10agents-10rules-10ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-10agents-10rules-10ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-10agents-10rules-10ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-10agents-10rules-10ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-10agents-10rules-10ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-20agents-20rules-20ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-20agents-20rules-20ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-20agents-20rules-20ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-20agents-20rules-20ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/gbp_usd_h1-20agents-20rules-20ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots

cp plots/usd_cad_h1-4agents-4rules-4ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-4agents-4rules-4ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-4agents-4rules-4ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-4agents-4rules-4ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-4agents-4rules-4ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-10agents-10rules-10ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-10agents-10rules-10ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-10agents-10rules-10ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-10agents-10rules-10ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-10agents-10rules-10ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-20agents-20rules-20ind-100gen_error_minimization.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-20agents-20rules-20ind-100gen_testing_fit.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-20agents-20rules-20ind-100gen_testing_profits.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-20agents-20rules-20ind-100gen_training_fit.pdf ../PhD-Thesis/img/plots
cp plots/usd_cad_h1-20agents-20rules-20ind-100gen_training_profits.pdf ../PhD-Thesis/img/plots
